### ISSUE TITLE
2.4.0 breaks the RethinkDB import tool

### ISSUE THREAD

**Issue by nicholastulach** [rethinkdb/rethinkdb-python#97] opened 2019-03-07 16:43 UTC
Breaking changes causing issues with other tools in the RethinkDB toolset, including the import tool.

**Comment by gabor-boros** [comment] 2019-03-08 11:38
@nicholastulach Hi! ✋ 
Could you please describe the issue a bit? What environment do you have, which python version, what did you executed, etc?

Please also provide a traceback if possible.

Thank you

**Comment by celogeek** [comment] 2019-03-09 16:15
The docker image "rethinkdb/latest" contains:
```
ii  python3.4                  3.4.2-1+deb8u2                   amd64        Interactive high-level object-oriented language (version 3.4)
```

When we try to install the package with the official docker image:
```
root@f63b1df539f7:/data# pip3 install --upgrade rethinkdb
Downloading/unpacking rethinkdb from https://files.pythonhosted.org/packages/3f/d0/38cdcc869ec7a3b0a936738b8bc4664d5d46f17037806076603f7d557d88/rethinkdb-2.4.0-py2.py3-none-any.whl#sha256=49132721e590a0a943084daac7e116492d892a952d67d7cb3938caa730872a08
  Downloading rethinkdb-2.4.0-py2.py3-none-any.whl (154kB): 154kB downloaded
Installing collected packages: rethinkdb
  Found existing installation: rethinkdb 2.3.0.post6
    Uninstalling rethinkdb:
      Successfully uninstalled rethinkdb
*** Error compiling '/tmp/pip-build-u5zjiwuf/rethinkdb/rethinkdb/trio_net/net_trio.py'...
  File "/tmp/pip-build-u5zjiwuf/rethinkdb/rethinkdb/trio_net/net_trio.py", line 57
    async def wait(self):
            ^
SyntaxError: invalid syntax

Successfully installed rethinkdb
Cleaning up...
```

Solution:
```
pip3 install 'rethinkdb<2.4'
```

**Comment by gabor-boros** [comment] 2019-03-13 13:17
@celogeek Ok the issue is the python version, but what I can not see right now is that how this part of the code was called. Hmm. This will need some investigation

**Comment by gabor-boros** [comment] 2019-04-18 08:14
Closing this issue due to this is related to https://github.com/rethinkdb/rethinkdb-python/issues/104

**Closed by gabor-boros** 2019-04-18 08:14 UTC
Labels: bug
